"""Initial Migration

Revision ID: 7795c5c21e69
Revises: 
Create Date: 2022-06-07 18:41:56.201986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7795c5c21e69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
